### ISSUE TITLE
Failing with Python 3.9 on Mac OS

### ISSUE THREAD

**Issue by rscheuermann** [transferwise/pipelinewise-target-snowflake#113]
**Describe the bug**
Failure to run the target on Python 3.9 on Mac OS due to joblib error

**To Reproduce**
1. Run python v3.9.0 on Mac OS
2. Run the target

**Stacktrace**

```
Traceback (most recent call last):
  File ".../proc_02/bin/target-snowflake", line 5, in <module>
    from target_snowflake import main
  File ".../proc_02/lib/python3.9/site-packages/target_snowflake/__init__.py", line 18, in <module>
    from joblib import Parallel, delayed, parallel_backend
  File ".../proc_02/lib/python3.9/site-packages/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File ".../proc_02/lib/python3.9/site-packages/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File ".../proc_02/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File ".../proc_02/lib/python3.9/site-packages/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File ".../proc_02/lib/python3.9/site-packages/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File ".../proc_02/lib/python3.9/site-packages/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File ".../proc_02/lib/python3.9/site-packages/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File ".../proc_02/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 152, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File ".../proc_02/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 133, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

**Your environment**
 - Version of target: latest
 - Version of python 3.9.0

**Comment by tirkarthi** [comment]
This seems to have been fixed in https://github.com/cloudpipe/cloudpickle/pull/269

**Comment by koszti** [comment]
This particular error in the topic should be fixed by now by [this PR](https://github.com/transferwise/pipelinewise-target-snowflake/commit/8e1452c7b528000941dcd5bc632bf3574535e2f8). More info in the [joblib 0.17.0 Release Notes](https://github.com/joblib/joblib/blob/master/CHANGES.rst#release-0170).

But very likely that it's still failing on python 3.9 because the snowflake-connector-python is not supported yet on python 3.9. More info at https://github.com/snowflakedb/snowflake-connector-python/issues/562

**Comment by Samira-El** [comment]
Closing this because the target isn't tested against python 3.9, downgrading to python 3.8 should fix this issue.
