### ISSUE TITLE
Failed to upload a file

### ISSUE THREAD

**Issue by aidan-melen** [transferwise/pipelinewise-target-snowflake#147]
**Describe the bug**
The target failed to upload a csv file to snowflake.

**To Reproduce**
- N/A this occurred out of the blue during normal operations. 

**Expected behavior**

Here is the stack trace:

```
KeyError: 'endpoint_resolver'
time=2021-02-25 17:06:17 name=snowflake.connector.file_transfer_agent level=ERROR message=Failed to upload a file: file=/tmp/records_jzcz74ft.csv, real file=/tmp/records_jzcz74ft.csv
Traceback (most recent call last):
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 437, in upload_one_file
    storage_client.upload_one_file_with_retry(meta)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/remote_storage_util.py", line 259, in upload_one_file_with_retry
    SnowflakeRemoteStorageUtil.upload_one_file(meta)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/remote_storage_util.py", line 107, in upload_one_file
    util_class.upload_file(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/s3_util.py", line 202, in upload_file
    akey.upload_file(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/boto3/s3/inject.py", line 278, in object_upload_file
    return self.meta.client.upload_file(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
    return transfer.upload_file(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 276, in upload_file
    future = self._manager.upload(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/s3transfer/manager.py", line 312, in upload
    return self._submit_transfer(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/s3transfer/manager.py", line 468, in _submit_transfer
    self._submission_executor.submit(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/s3transfer/futures.py", line 467, in submit
    future = ExecutorFuture(self._executor.submit(task))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 181, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Your environment**
 - Version of target: 1.10.0
 - Version of python: 3.8

**additional information**

The weird thing about this error is that we are instantiating the s3transfer lib when we are not specifying any S3 configuration.

Here is a scrubbed example of our configuration for the target:

```json
{
    "account": "blarg",
    "user": "BLARG_USER",
    "password": "blarg",
    "role": "BLARG",
    "warehouse": "BLARG",
    "dbname": "BLARGY_DATABASE",
    "default_target_schema": "WOOTRIC",
    "file_format": "BLARGY_DATABASE.BLARGY_SCHEMA.BLARG_CSV"
  }
```

**Comment by Samira-El** [comment]
Hey Aidan,

Can you please share more logs? specifically those logged by the target itself before the `KeyError: 'endpoint_resolver'` happened. 

Also, are you using this target within PipelineWise or standalone?

**Comment by aidan-melen** [comment]
@Samira-El of course. We encounter the same error this morning.

```
time=2021-02-26 18:32:37 name=target_snowflake level=INFO message=Uploading 278 rows to stage
time=2021-02-26 18:32:37 name=target_snowflake level=INFO message=Target internal stage: WOOTRIC.%"RESPONSES", local file: /tmp/records_m360_nx_.csv, key: records_m360_nx_.csv
time=2021-02-26 18:32:37 name=target_snowflake level=INFO message=PUT 'file:///tmp/records_m360_nx_.csv' '@WOOTRIC.%"RESPONSES"' SOURCE_COMPRESSION=GZIP
time=2021-02-26 18:32:37 name=target_snowflake level=INFO message=Uploading 2224 rows to stage
time=2021-02-26 18:32:37 name=target_snowflake level=INFO message=Target internal stage: WOOTRIC.%"DECLINES", local file: /tmp/records_zcj9zts2.csv, key: records_zcj9zts2.csv
time=2021-02-26 18:32:37 name=target_snowflake level=INFO message=PUT 'file:///tmp/records_zcj9zts2.csv' '@WOOTRIC.%"DECLINES"' SOURCE_COMPRESSION=GZIP
time=2021-02-26 18:32:38 name=target_snowflake level=INFO message=Uploading 2541 rows to stage
time=2021-02-26 18:32:38 name=target_snowflake level=INFO message=Target internal stage: WOOTRIC.%"END_USERS", local file: /tmp/records__yu1bbv6.csv, key: records__yu1bbv6.csv
time=2021-02-26 18:32:38 name=target_snowflake level=INFO message=PUT 'file:///tmp/records__yu1bbv6.csv' '@WOOTRIC.%"END_USERS"' SOURCE_COMPRESSION=GZIP
time=2021-02-26 18:32:40 name=target_snowflake level=INFO message=Loading 278 rows into 'WOOTRIC."RESPONSES"'
time=2021-02-26 18:32:41 name=target_snowflake level=INFO message=Loading into WOOTRIC."RESPONSES": {"inserts": 257, "updates": 21, "size_bytes": 12340}
time=2021-02-26 18:32:42 name=target_snowflake level=INFO message=Deleting records_m360_nx_.csv from stage
time=2021-02-26 18:32:42 name=target_snowflake level=INFO message=Deleting records_m360_nx_.csv from internal snowflake stage
Traceback (most recent call last):
  File "/app/target-snowflake-venv/bin/target-snowflake", line 10, in <module>
    sys.exit(main())
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/__init__.py", line 452, in main
    persist_lines(config, singer_messages, table_cache)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/__init__.py", line 312, in persist_lines
    flushed_state = flush_streams(records_to_load, row_count, stream_to_sync, config, state, flushed_state)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/__init__.py", line 361, in flush_streams
    Parallel()(delayed(load_stream_batch)(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/__init__.py", line 397, in load_stream_batch
    flush_records(stream, records_to_load, row_count[stream], db_sync, temp_dir, no_compression)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/__init__.py", line 429, in flush_records
    s3_key = db_sync.put_to_stage(csv_file, stream, row_count, temp_dir=temp_dir)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/db_sync.py", line 455, in put_to_stage
    return self.uploadClient.upload_file(file, stream, temp_dir)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/target_snowflake/snowflake_upload_client.py", line 26, in upload_file
    connection.cursor().execute(cmd)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 572, in execute
    sf_file_transfer_agent.execute()
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 216, in execute
    self._transfer_accelerate_config()
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/file_transfer_agent.py", line 289, in _transfer_accelerate_config
    client = SnowflakeRemoteStorageUtil.create_client(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/remote_storage_util.py", line 57, in create_client
    return util_class.create_client(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/snowflake/connector/s3_util.py", line 75, in create_client
    client = boto3.resource(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/boto3/session.py", line 384, in resource
    client = self.client(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/botocore/session.py", line 827, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/botocore/session.py", line 700, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/app/target-snowflake-venv/lib/python3.8/site-packages/botocore/session.py", line 928, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'
```

**Comment by aidan-melen** [comment]
@Samira-El
We are running the target "standalone" in a docker container.

**Comment by Samira-El** [comment]
Hey Aidan,
Apologies for not getting back sooner.

So you're using internal stage, it's a new feature added by an external contributor but we don't use it.
It seems like the issue is from Snowflake connector, I found a similar issue: https://github.com/snowflakedb/snowflake-connector-python/issues/156

Not sure what can be done from target-snowflake side, maybe you can set parallelism in the config to 1 and see how it goes?

**Comment by aidan-melen** [comment]
@Samira-El that seems like a solid suggestion. I will give that a shot and see what happens.

**Comment by aidan-melen** [comment]
@Samira-El It has been 4 days and we haven't encountered the this issue since configuring the parallel setting. I will mark this as a win. thank you
