### ISSUE TITLE
Error while executing MERGE query for table, Boolean value '' is not recognized

### ISSUE THREAD

**Issue by nauxliu** [transferwise/pipelinewise-target-snowflake#267]
**Describe the bug**
If there's a nullable bool column in the table, LOG_BASED incremental sync fails with the error when merging: Boolean value '' is not recognized

**Expected behavior**
The sync should success.

**Screenshots**

**Your environment**
 - Version of target: 2.0.1
 - Version of python:  python:3.8-slim-buster

**Additional context**

```
Traceback (most recent call last):
  File "/app/pipelinewise/cli/pipelinewise.py", line 1260, in run_tap
    self.run_tap_singer(
  File "/app/pipelinewise/cli/pipelinewise.py", line 1068, in run_tap_singer
    commands.run_command(command, self.tap_run_log_file, update_state_file)
  File "/app/pipelinewise/cli/commands.py", line 489, in run_command
    raise RunCommandException(
pipelinewise.cli.commands.RunCommandException: Command failed. Return code: 1
Error(s) found:
time=2022-04-23 03:28:49 logger_name=target_snowflake log_level=ERROR message=Error while executing MERGE query for table "ppw_db."USERS"" in stream "xxxx-users"
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
    cursor.errorhandler(connection, cursor, error_class, error_value)
snowflake.connector.errors.ProgrammingError: 100037 (22018): Boolean value '' is not recognized
```

**Comment by nauxliu** [comment]
Turns out it is because the file format created with Terraform set the `empty_field_as_null` to `false` by default.
