### ISSUE TITLE
MySQL to Snowflake Log Based replication parsing error

### ISSUE THREAD

**Issue by ahuynh3** [transferwise/pipelinewise-target-snowflake#51]
When trying to replicate data (Log Based) from MySQL to Snowflake following this specific flow, we run into the following error:

*Flow*  
Replicate data (Initial run) --> New data gets inserted into a timestamp column --> Timestamp column gets dropped --> Replicate date (next run, this causes the error shown below)

*Error*
```
Traceback (most recent call last):
  File "/app/.virtualenvs/target-snowflake/bin/target-snowflake", line 11, in <module>
    load_entry_point('pipelinewise-target-snowflake', 'console_scripts', 'target-snowflake')()
  File "/app/singer-connectors/target-snowflake/target_snowflake/__init__.py", line 430, in main
    persist_lines(config, singer_messages, information_schema_cache)
  File "/app/singer-connectors/target-snowflake/target_snowflake/__init__.py", line 174, in persist_lines
    adjust_timestamps_in_record(o['record'], schemas[stream])
  File "/app/singer-connectors/target-snowflake/target_snowflake/__init__.py", line 135, in adjust_timestamps_in_record
    reset_new_value(record, key, schema['properties'][key]['format'])
  File "/app/singer-connectors/target-snowflake/target_snowflake/__init__.py", line 121, in reset_new_value
    parser.parse(record[key])
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not int
```

**Comment by Samira-El** [comment]
Hey, thanks for reporting this.

It's not supposed to happen, because the parsing only happen when the json type is string and format is either `time`, `date` or `datetime`, so the value should be a string but the it was int.

**Comment by Samira-El** [comment]
Closing due to inactivity!
