### ISSUE TITLE
Bug: Empty Schema Snowflake, Table Cache enabled, KeyError

### ISSUE THREAD

**Issue by paulmonk** [transferwise/pipelinewise-target-snowflake#78]
Hello, Thanks for creating this library, it is much appreciated.

I started using this today and came across a bug.
If you use the target (outside of the pipelinewise framework) with a schema (let's say called "example" - name does not matter) that exists in Snowflake, but has zero tables, with a `--config` file parsed into Python that contains the following (amongst the other required config keys/values):

- `default_target_schema: "example"`
- `disable_table_cache: False`

You will get a `KeyError` as so when the target runs:
```python
[2020-06-08 15:44:20,291] {{bash_operator.py:126}} INFO - time=2020-06-08 15:44:20 name=target_snowflake level=INFO message=Getting catalog objects from table cache...
[2020-06-08 15:44:23,920] {{bash_operator.py:126}} INFO - Traceback (most recent call last):
[2020-06-08 15:44:23,920] {{bash_operator.py:126}} INFO -   File "target-snowflake/bin/target-snowflake", line 8, in <module>
[2020-06-08 15:44:23,920] {{bash_operator.py:126}} INFO -     sys.exit(main())
[2020-06-08 15:44:23,920] {{bash_operator.py:126}} INFO -   File "target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 446, in main
[2020-06-08 15:44:23,921] {{bash_operator.py:126}} INFO -     persist_lines(config, singer_messages, table_cache)
[2020-06-08 15:44:23,921] {{bash_operator.py:126}} INFO -   File "target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 282, in persist_lines
[2020-06-08 15:44:23,921] {{bash_operator.py:126}} INFO -     stream_to_sync[stream].create_schema_if_not_exists()
[2020-06-08 15:44:23,921] {{bash_operator.py:126}} INFO -   File "target-snowflake/lib/python3.7/site-packages/target_snowflake/db_sync.py", line 551, in create_schema_if_not_exists
[2020-06-08 15:44:23,921] {{bash_operator.py:126}} INFO -     schema_rows = list(filter(lambda x: x['SCHEMA_NAME'] == schema_name.upper(), self.table_cache))
[2020-06-08 15:44:23,921] {{bash_operator.py:126}} INFO -   File "target-snowflake/lib/python3.7/site-packages/target_snowflake/db_sync.py", line 551, in <lambda>
[2020-06-08 15:44:23,922] {{bash_operator.py:126}} INFO -     schema_rows = list(filter(lambda x: x['SCHEMA_NAME'] == schema_name.upper(), self.table_cache))
[2020-06-08 15:44:23,922] {{bash_operator.py:126}} INFO - KeyError: 'SCHEMA_NAME'
[2020-06-08 15:44:24,029] {{bash_operator.py:130}} INFO - Command exited with return code 1
```

This is because the result returned to the `table_cache` will be `[{'status': 'Statement executed successfully.'}]` which of course is missing the referenced key.

Version used: `pipelinewise-target-snowflake==1.6.4`

Thanks.

**Comment by koszti** [comment]
oh, thanks for reporting this. Something that needs to be fixed.

**Comment by koszti** [comment]
fixed and will be released to PyPI soon in the next version

**Comment by aaronsteers** [comment]
@paulmonk -Thanks for raising this. I had the same issue. @koszti - as always, thanks very much for your work on this. I'm excited to see this is in already on the path to being resolved.

**Comment by paulmonk** [comment]
Thanks @koszti for your work on this, much appreciated!

No worries @aaronsteers I guess lightning does indeed strike twice! :)

**Comment by aaronsteers** [comment]
@koszti - I'm not sure how timing works for PiPy but for what it's worth, I updated my fork with the changes from master branch and that did indeed resolve my error when working with empty schemas. 👍

**Comment by koszti** [comment]
this has been released to [PyPI as part of pipelinewise-target-snowflake 1.6.6](https://pypi.org/project/pipelinewise-target-snowflake/)
